### ISSUE TITLE
AFB blocks vu+ Box in VTi

### ISSUE THREAD

**Issue by Dieter59** [Dima73/automatic-full-backup#12]
during automatically started backup the remote control of vu+ boxes is blocked and the spinner is shown. If you start AFB manually the box is fully controlable with the remote control. Is that a wanted behaviour?
Version 5.9 and 6.2 tested with VU+ Duo2 and VTi 13.0.2

**Comment by Dima73** [comment]
For automatic behavior, this is not configurable.
To create a good backup it is better to use the idle mode.

**Comment by Dieter59** [comment]
Ok thank you. I close the issue!
