### ISSUE TITLE
Socket ignored

### ISSUE THREAD

**Issue by frankviana** [Dima73/automatic-full-backup#16]
I have Vu zero 4k and appear this message:

tar: ./var/lib/samba/private/msg.sock/1139: sockete ignored

1139 until 1347

See the pictures:

https://postimg.cc/gallery/1yhym74bc/

**Comment by Dima73** [comment]
https://github.com/Dima73/automatic-full-backup/commit/d82bfb0c491d0c08100cc22e48dd64d589c962b2#diff-1aa181c04b19f5ebb05c757570f26afdR174
