### ISSUE TITLE
Vu+ Duo 4k & Zero 4k Support

### ISSUE THREAD

**Issue by ghost** [Dima73/automatic-full-backup#17]
Hi Dimitrij, I really like your plugin and hope that you will take some time and adjust automatic-fullbackup-vu4k.sh so Duo 4k and Zero 4k can also be supported.  

I think only Uno 4k and Zero 4k have no display and need force.update files. 

root@vuduo4k:~# cat /proc/stb/info/vumodel                                                                                                                                                                         
duo4k
Kernel / Driver: 
4.1.45 / 4.1.45-20181130.r0
        
Thank you!

#!/bin/sh
#

VERSION="vu4k models- 20/11/2017\ncreator of the script Dimitrij (http://forums.openpli.org)\n"
DIRECTORY="$1"
START=$(date +%s)
DATE=`date +%Y%m%d_%H%M`
IMAGEVERSION=`date +%Y%m%d`
MKFS=/bin/tar
BZIP2=/usr/bin/bzip2
ROOTFSTYPE="rootfs.tar.bz2"
WORKDIR="$DIRECTORY/bi"

getaddr() {
	python - $1 $2<<-"EOF"
		from sys import argv
		filename = argv[1]
		address = int(argv[2])
		fh = open(filename,'rb')
		header = fh.read(2048)
		fh.close()
		print "%d" % ( (ord(header[address+2]) <<16 ) | (ord(header[address+1]) << 8) |  ord(header[address]) )
	EOF
}

if [ -f /etc/issue ] ; then
	ISSUE=`cat /etc/issue | grep . | tail -n 1 ` 
	IMVER=${ISSUE%?????}
elif [ -f /etc/bhversion ] ; then
	ISSUE=`cat /etc/bhversion | grep . | tail -n 1 ` 
	IMVER=${ISSUE%?????}
elif [ -f /etc/vtiversion.info ] ; then
	ISSUE=`cat /etc/vtiversion.info | grep . | tail -n 1 ` 
	IMVER=${ISSUE%?????}
elif [ -f /etc/vtiversion.info ] ; then
	ISSUE=`cat /etc/vtiversion.info | grep . | tail -n 1 ` 
	IMVER=${ISSUE%?????}
elif [ -f /proc/stb/info/vumodel ] && [ -f /etc/version ] ; then
	ISSUE=`cat /etc/version | grep . | tail -n 1 ` 
	IMVER=${ISSUE%?????}
else
	IMVER="unknown"
fi

echo "Script date = $VERSION\n"
echo "Back-up media = $DIRECTORY\n"
df -h "$DIRECTORY"
echo "Back-up date_time = $DATE\n"
echo "Working directory = $WORKDIR\n"
echo -n "Drivers = "
opkg list-installed | grep dvb-proxy
CREATE_ZIP="$2"
IMAGENAME="$3"

if [ -f /proc/stb/info/vumodel ] ; then
	MODEL=$( cat /proc/stb/info/vumodel )
	if [ $MODEL = "solo4k" ] ; then
		echo "Found VU+ Solo 4K\n"
		MTD_KERNEL="mmcblk0p1"
		KERNELNAME="kernel_auto.bin"
	elif [ $MODEL = "uno4k" ] ; then
		echo "Found VU+ Uno 4K\n"
		MTD_KERNEL="mmcblk0p1"
		KERNELNAME="kernel_auto.bin"
	elif [ $MODEL = "uno4kse" ] ; then
		echo "Found VU+ Uno 4K se\n"
		MTD_KERNEL="mmcblk0p1"
		KERNELNAME="kernel_auto.bin"
	elif [ $MODEL = "ultimo4k" ] ; then
		echo "Found VU+ Ultimo 4K\n"
		MTD_KERNEL="mmcblk0p1"
		KERNELNAME="kernel_auto.bin"
	**elif [ $MODEL = "duo4k" ] ; then
		echo "Found VU+ Duo 4K\n"
		MTD_KERNEL="mmcblk0p1"
		KERNELNAME="kernel_auto.bin"
	elif [ $MODEL = "zero4k" ] ; then
		echo "Found VU+ Zero 4K\n"
		MTD_KERNEL="mmcblk0p1"
		KERNELNAME="kernel_auto.bin"**
	else
		echo "No supported receiver found!\n"
		exit 0
	fi
	TYPE=VU
	SHOWNAME="Vu+ $MODEL"
	MAINDEST="$DIRECTORY/vuplus/$MODEL"
	EXTRA="$DIRECTORY/automatic_fullbackup/$DATE/vuplus"
	echo "Destination        = $MAINDEST\n"
else
	echo "No supported receiver found!\n"
	exit 0
fi

if [ ! -f $MKFS ] ; then
	echo "NO TAR FOUND, ABORTING\n"
	exit 0
fi
if [ ! -f "$BZIP2" ] ; then 
	echo "$BZIP2 not installed yet, now installing\n"
	opkg update > /dev/null 2>&1
	opkg install bzip2 > /dev/null 2>&1
	echo "Exit, try again\n"
	sleep 10
	exit 0
fi

echo "Starting Full Backup!\nOptions control panel will not be available 2-15 minutes.\nPlease wait ..."
echo "--------------------------"

control_c(){
   echo "Control C was pressed, quiting..."
   umount /tmp/bi/root 2>/dev/null
   rmdir /tmp/bi/root 2>/dev/null
   rmdir /tmp/bi 2>/dev/null
   rm -rf "$WORKDIR" 2>/dev/null
   exit 255
}
trap control_c SIGINT

echo "\nWARNING!\n"
echo "To stop creating a backup, press the Menu button.\n"
sleep 2

## PREPARING THE BUILDING ENVIRONMENT
rm -rf "$WORKDIR"
echo "Remove directory   = $WORKDIR\n"
mkdir -p "$WORKDIR"
echo "Recreate directory = $WORKDIR\n"
mkdir -p /tmp/bi/root
echo "Create directory   = /tmp/bi/root\n"
sync
mount --bind / /tmp/bi/root

#dd if=/dev/$MTD_KERNEL of=$WORKDIR/kernel.dump
#ADDR=$(getaddr $WORKDIR/kernel.dump 44)
#dd if=$WORKDIR/kernel.dump of=$WORKDIR/$KERNELNAME bs=$ADDR count=1 && rm $WORKDIR/kernel.dump
dd if=/dev/$MTD_KERNEL of=$WORKDIR/$KERNELNAME > /dev/null 2>&1
echo "Kernel resides on /dev/$MTD_KERNEL\n" 

echo "Start creating rootfs.tar\n"
#$MKFS -jcf $WORKDIR/$ROOTFSTYPE -C /tmp/bi/root .
$MKFS -cf $WORKDIR/rootfs.tar -C /tmp/bi/root --exclude=/var/nmbd/* .
$BZIP2 $WORKDIR/rootfs.tar

TSTAMP="$(date "+%Y-%m-%d-%Hh%Mm")"

if [ $TYPE = "VU" ] ; then
	rm -rf "$MAINDEST"
	echo "Removed directory  = $MAINDEST\n"
	mkdir -p "$MAINDEST" 
	echo "Created directory  = $MAINDEST\n"
	mv "$WORKDIR/$KERNELNAME" "$MAINDEST/$KERNELNAME"
	mv "$WORKDIR/$ROOTFSTYPE" "$MAINDEST/$ROOTFSTYPE"
	echo "$MODEL-$IMAGEVERSION" > "$MAINDEST/imageversion"
	if [ $MODEL = "uno4k" ] || [ $MODEL = "uno4kse" ] ; then
		echo "rename this file to 'force.update' when need confirmation" > "$MAINDEST/noforce.update"
	else
		echo "This file forces a reboot after the update" > "$MAINDEST/reboot.update"
	fi
	if [ -z "$CREATE_ZIP" ] ; then
		mkdir -p "$EXTRA/$MODEL"
		echo "Created directory  = $EXTRA/$MODEL\n"
		touch "$MAINDEST/$IMVER"
		cp -r "$MAINDEST" "$EXTRA" 
		touch "$DIRECTORY/automatic_fullbackup/.timestamp"
	else
		if [ $CREATE_ZIP != "none" ] ; then
			echo "Create zip archive..."
			cd $DIRECTORY && $CREATE_ZIP -r $DIRECTORY/backup-$IMAGENAME-$MODEL-$TSTAMP.zip . -i /$MODEL/*
			cd
		fi
	fi
	if [ -f "$MAINDEST/rootfs.tar.bz2" -a -f "$MAINDEST/$KERNELNAME" ] ; then
		echo " "
		echo "BACK-UP MADE SUCCESSFULLY IN: $MAINDEST\n"
	else
		echo " "
		echo "Image creation FAILED!\n"
	fi
fi
umount /tmp/bi/root
rmdir /tmp/bi/root
rmdir /tmp/bi
rm -rf "$WORKDIR"
sleep 5
END=$(date +%s)
DIFF=$(( $END - $START ))
MINUTES=$(( $DIFF/60 ))
SECONDS=$(( $DIFF-(( 60*$MINUTES ))))
if [ $SECONDS -le  9 ] ; then 
	SECONDS="0$SECONDS"
fi
echo "BACKUP FINISHED IN $MINUTES.$SECONDS MINUTES\n"
exit

**Comment by ghost** [comment]
If you need any debug information from me as a zero 4k and duo 4k user please let me know?! Thank you!

**Comment by ghost** [comment]
Attached a debug log from VTI Image 14.0.1 after vti Image Backup successfully created a backup on Duo 4k. Hope it helps. Thank you!
[dvbapp2_debug_2018-12-03_151322.log.txt](https://github.com/Dima73/automatic-full-backup/files/2639815/dvbapp2_debug_2018-12-03_151322.log.txt)

**Comment by Dima73** [comment]
elif [ $MODEL = "duo4k" ] ; then
echo "Found VU+ Duo 4K\n"
MTD_KERNEL="mmcblk0p1"
???
https://github.com/oe-alliance/oe-alliance-core/blob/4.2/meta-brands/meta-vuplus/conf/machine/vuduo4k.conf#L7

elif [ $MODEL = "zero4k" ] ; then
echo "Found VU+ Zero 4K\n"
MTD_KERNEL="mmcblk0p1"
???

https://github.com/oe-alliance/oe-alliance-core/blob/4.2/meta-brands/meta-vuplus/conf/machine/vuzero4k.conf#L7

Is true?

**Comment by ghost** [comment]
No, and it does not work with the adjusted script. I need your help. If there is anything I can do or Test to help let me know.

**Comment by Dima73** [comment]
https://github.com/Dima73/automatic-full-backup/commit/d82bfb0c491d0c08100cc22e48dd64d589c962b2

**Comment by ash-tsc** [comment]
Thank you! : Looks good! Testing. 
![thankyou](https://user-images.githubusercontent.com/16594981/49610177-135fe200-f99e-11e8-99ea-de0489203cef.jpg)

**Comment by ash-tsc** [comment]
Zero4k also works. It just did not because I am stupid and did not know how to do it right. 
Thank you again. Dima -🥇 
![zero4k](https://user-images.githubusercontent.com/16594981/49610527-20310580-f99f-11e8-9da3-7b9cb65a9e4b.jpg)

**Comment by ghost** [comment]
:Thank! All three boxes (Ultimo 4k / Duo 4k & Zero 4k) work like a charme with new build 6,6! Can I somehow buy you a beer?

![1](https://user-images.githubusercontent.com/13977492/49612013-ab13ff00-f9a3-11e8-92fb-99fdb10bf7bf.jpg)
![2](https://user-images.githubusercontent.com/13977492/49612017-acddc280-f9a3-11e8-9e54-2410dd154888.jpg)
![3](https://user-images.githubusercontent.com/13977492/49612019-ae0eef80-f9a3-11e8-9b84-38b4442e6f13.jpg)

**Comment by Dima73** [comment]
Beer - that would be great!
PayPal dima-73@inbox.lv

**Comment by ghost** [comment]
Thanks!! You make people happy! Keep it up! 

Gruss Tim

**Comment by Dima73** [comment]
@edelknecht
thank you very much for the beer.

**Comment by ash-tsc** [comment]
Your welcome!

Gruss Tim

Am 07.12.2018 um 08:16 schrieb Dimitrij <notifications@github.com<mailto:notifications@github.com>>:


@edelknecht<https://github.com/edelknecht>
thank you very much for the beer.
