### ISSUE TITLE
Feature Request: Manual type in of backup location

### ISSUE THREAD

**Issue by Silverscape** [Dima73/automatic-full-backup#18]
Hi,

I would like to make a feature request:
On the VU+ models, it is not easily possible to select a (remote) backup location with different path, for example a NAS.

In Automatic Full Backup I can only choose between USB, mounted network share (autofs), etc.
In my example I have autofs correctly configured and have 4 mounts, but in automatic full backup plugin I onle get 2 destination points for the backup:
/media/usb
/media/net/autofs/NAS

I dont want the backup to be in /media/net/autofs/NAS. I rather would like to have the backup in a different folder location, in example /media/net/autofs/NAS/backups.
My problem is that the plugin gives me only the 2 backup destinations mentioned above.
It would be nice, if we could also add a new backup location manually with the On-Screen-Keyboard for example. Or you could make the mounted network share detection on the VU+ models a little bit better to also find and display the other correctly mounted autofs shares on the box.

Many thanks in advance.

**Comment by Dima73** [comment]
Sorry, I do not plan to make such changes.
