### ISSUE TITLE
VU+ Duo 4k only works on manual backup

### ISSUE THREAD

**Issue by florie1706** [Dima73/automatic-full-backup#19]
Hi,

thanks to your version 6.6 which works when I do a command line backup, but doesn't on the automatic backup function. That means that only these files will be saved on the automatic backup:

```
-rw-r--r--    1 nobody   nogroup         15 Jan 13 04:00 imageversion
-rw-r--r--    1 nobody   nogroup   16777216 Jan 13 04:00 kernel_auto.bin
-rw-r--r--    1 nobody   nogroup         83 Jan 13 04:00 nomkpart.update
-rw-r--r--    1 nobody   nogroup         43 Jan 13 04:00 reboot.update
```

As you can see it differs from the manual backup which saves these files:

```
-rw-r--r--    1 nobody   nogroup         15 Jan 13 08:49 imageversion
-rw-r--r--    1 nobody   nogroup   16777216 Jan 13 08:49 kernel_auto.bin
-rw-r--r--    1 nobody   nogroup         83 Jan 13 08:49 nomkpart.update
-rw-r--r--    1 nobody   nogroup          0 Jan 13 08:49 openpli 7.0-rc
-rw-r--r--    1 nobody   nogroup         43 Jan 13 08:49 reboot.update
-rw-r--r--    1 nobody   nogroup   68019059 Jan 13 08:49 rootfs.tar.bz2
```

Any chance to check why this behavior happens?

**Comment by Dima73** [comment]
How do you make manual backup?
Show an example.

**Comment by florie1706** [comment]
` /usr/lib/enigma2/python/Plugins/Extensions/FullBackup/automatic-fullbackup-vu4k.sh /media/net/Festplatte/`

**Comment by Dima73** [comment]
Very strange.
I do not even know what to say.

Maybe this:
media/net/Festplatte/

Try to use a flash drive(media/usb) for backup.

**Comment by Dima73** [comment]
https://www.vuplus-support.org/wbb4/index.php?thread/99285-automaticfullbackup/&postID=1837037#post1837037

**Comment by florie1706** [comment]
Ok, /media/hdd (internal hdd) does work. So I now run a cronjob, that moves form internal to networ drive ;)

**Comment by Dima73** [comment]
Fine.
