### ISSUE TITLE
Improve German translation / Typo in de.po line 144 /msgstr "Manuell"

### ISSUE THREAD

**Issue by ghost** [Dima73/automatic-full-backup#2]
Hi, please spell Manuell with a capital M and not manuell so all buttons are spellt with capitals and it looks perfect. 

msgid "Manual"
msgstr "Manuell"

Thank you for this great plugin!  

![image](https://cloud.githubusercontent.com/assets/13977492/21714406/15ec6686-d3ff-11e6-9489-5e1c46a0b400.png)

**Comment by Dima73** [comment]
https://github.com/Dima73/automatic-full-backup/commit/68c50e39863691b1d535769fce853a85e958c821
