### ISSUE TITLE
Py3

### ISSUE THREAD

**Issue by pingwin1908** [Dima73/automatic-full-backup#28]
Is it possible to modify the plug for py3?

**Comment by Dima73** [comment]
todo...

**Comment by pingwin1908** [comment]
when it is possible to modify?

**Comment by Dima73** [comment]
August

**Comment by pingwin1908** [comment]
not bad :)

**Comment by mensa84** [comment]
Hi, is there already a working version for openATV 7.0 or 7.1?

**Comment by pingwin1908** [comment]
> August
August is over and nothing :)

**Comment by Dima73** [comment]
> > August
> > August is over and nothing :)

Have you personally tested it and it doesn't work?
Is there an error log?

**Comment by mensa84** [comment]
How could I test it?
Is there an IPK to install? I don't know how to run code from Github on my box, so could you please provide an IPK file?

**Comment by pingwin1908** [comment]
> > > August
> > > August is over and nothing :)
> 
> Have you personally tested it and it doesn't work? Is there an error log?

yes
i try enigma2-plugin-extensions-automatic-fullbackup_6.6_all
 but on OATV7.1 is https://megawrzuta.pl/download/df964bd038a3bee56576c8e2aafce60e.html

**Comment by Dima73** [comment]
https://github.com/Dima73/automatic-full-backup/blob/master/enigma2-plugin-extensions-automatic-fullbackup_7.0_all.ipk

**Comment by mensa84** [comment]
> https://github.com/Dima73/automatic-full-backup/blob/master/enigma2-plugin-extensions-automatic-fullbackup_7.0_all.ipk

Thank you, I installed it now with IPK intaller on my Vu+ Uno 4K with oATV 7.1 but it does not appear in Plugin Manager. How can I start it?

![image](https://user-images.githubusercontent.com/30125802/190988928-38974eac-b366-4e89-8b19-8ad3a4334f6d.png)

**Comment by mensa84** [comment]
> > https://github.com/Dima73/automatic-full-backup/blob/master/enigma2-plugin-extensions-automatic-fullbackup_7.0_all.ipk
> 
> Thank you, I installed it now with IPK intaller on my Vu+ Uno 4K with oATV 7.1 but it does not appear in Plugin Manager. How can I start it?
> 
> ![image](https://user-images.githubusercontent.com/30125802/190988928-38974eac-b366-4e89-8b19-8ad3a4334f6d.png)

I had to reboot it and now it appears. I started the first Backup right now and it looks good:

![image](https://user-images.githubusercontent.com/30125802/190989455-80f9eda1-44c0-477b-b639-343d1d6be452.png)

I will try more and some automatic backups now and give feedback here.

**Comment by Dima73** [comment]
This plugin only broadcom box.
`def Plugins(**kwargs):
	if os.path.exists("/proc/hisi"):
		return []`

**Comment by mensa84** [comment]
> This plugin only broadcom box. `def Plugins(**kwargs): if os.path.exists("/proc/hisi"): return []`

Is my Vu+ Uno 4K a broadcom box?

**Comment by Dima73** [comment]
yes

**Comment by pingwin1908** [comment]
![Bez tytułu](https://user-images.githubusercontent.com/106807204/190992115-10d57ba1-68e3-4cf6-927c-91beb55138e5.jpg)
![1_0_1_1138_2AF8_13E_820000_0_0_0_20220919114615](https://user-images.githubusercontent.com/106807204/190991764-ecfad854-383b-4e21-b4ea-b7600188ebf9.jpg)
 don`t restore anyway :(

> > don`t restore anyway :(
> 
[PY3.zip](https://github.com/Dima73/automatic-full-backup/files/9597895/PY3.zip)

> What receiver model?

zgemma h7s
but look at my backup scripts it working and restore as imag menu mode

**Comment by Dima73** [comment]
>  don`t restore anyway :(

What receiver model?
zgemmaH7?

**Comment by Dima73** [comment]
Rename linuxke.bin as kernel.bin

**Comment by pingwin1908** [comment]
> 

the same 
look at my scripts 
[PY3.zip](https://github.com/Dima73/automatic-full-backup/files/9597927/PY3.zip)

**Comment by mensa84** [comment]
Backup and restore worked, thank you!

![image](https://user-images.githubusercontent.com/30125802/190992286-7ce61489-eabb-4988-9684-15abce7a3265.png)

![image](https://user-images.githubusercontent.com/30125802/190992299-a73227f5-831b-4a4c-a4ee-a0ec92afb476.png)
@pingwin1908 Are you in that directory when you press the green button to start flash?
![image](https://user-images.githubusercontent.com/30125802/190992319-2c2815da-5468-454d-85ca-b7f207a71a1e.png)

![image](https://user-images.githubusercontent.com/30125802/190992346-0e9cb852-c367-40f7-aa87-5c2a52a57b42.png)

**Comment by pingwin1908** [comment]
OK rename to kernel.bin and if i restore as first partition Standard ( root and kernel ) tuner faild 
need to flash from usb

**Comment by Dima73** [comment]
I can't help you.
Once upon a time, I had a zgemma H7 and the backup worked.
Now I have not had it for a long time and apparently a lot has changed.
Is it interesting that the BackupSuite plugin works?

**Comment by mensa84** [comment]
@Dima73 Could you please tell me if there is a settings file for AutomaticFullBackup in the file system and where it is located?
So that I could look in an old backup for my settings.

**Comment by pingwin1908** [comment]
> I can't help you.
> Once upon a time, I had a zgemma H7 and the backup worked.
> Now I have not had it for a long time and apparently a lot has changed.
> Is it interesting that the BackupSuite plugin works?

BackupSuite working but only for OpenPLi and only first slot backup and restore 
OATV has got has its own backup and restore system in imag and working very good but not in timer only manually

**Comment by Dima73** [comment]
> @Dima73 Could you please tell me if there is a settings file for AutomaticFullBackup in the file system and where it is located?
> So that I could look in an old backup for my settings.

config.plugins.fullbackup

**Comment by pingwin1908** [comment]
> > Could you please tell me if there is a settings file for AutomaticFullBackup in the file system and where it is located?
> > So that I could look in an old backup for my settings.
> 
> config.plugins.fullbackup

only in /etc/enigma2/settings
config.plugins.extra_fullbackup.day_backup.1=False
config.plugins.fullbackup.enabled=True
config.plugins.fullbackup.where=/media/hdd

**Comment by mensa84** [comment]
Is there a working version for openATV 7.4?

**Comment by Dima73** [comment]
I don't know.

**Comment by mensa84** [comment]
Is 7.0 the latest version? Or is there any newer?

**Comment by Dima73** [comment]
https://github.com/Dima73/automatic-full-backup/blob/master/enigma2-plugin-extensions-automatic-fullbackup_7.1_all.ipk

**Comment by mensa84** [comment]
Oh cool, thanks! Was there right now a new release? Is there a changelog?

**Comment by Dima73** [comment]
Support py3
[python3](https://github.com/Dima73/automatic-full-backup/commit/13a8bb573f38aeb2bc2892b8f4d562334617f67b)

**Comment by mensa84** [comment]
Where is the latest release build please?

**Comment by Dima73** [comment]
openPli develop image or this https://github.com/Dima73/automatic-full-backup/blob/master/enigma2-plugin-extensions-automatic-fullbackup_7.1_all.ipk 7.1 ipk
