### ISSUE TITLE
Restore not possible on HDD with Ultimo4K(VU) Image VTI 11.0.1

### ISSUE THREAD

**Issue by Drickes** [Dima73/automatic-full-backup#3]
After discussing the topic in www.vuplus-support.org I discribe my problem here.

After installing the plugin it*s no problem to make a backup on HDD, but the restore fails.
My Ultimo4K has a internal 4TB HDD. 

![afb_fehler1](https://cloud.githubusercontent.com/assets/24958767/21718482/0c1e4da4-d418-11e6-8863-6150ee9ff3c8.jpg)
![afb_fehler2](https://cloud.githubusercontent.com/assets/24958767/21718481/0c1b8b14-d418-11e6-90f1-77f2af6e6756.jpg)
![afb_start](https://cloud.githubusercontent.com/assets/24958767/21718483/0c1eba82-d418-11e6-891a-a49b0f4317c6.jpg)

I forgot: Image ist VTI 11.0.1

**Comment by betacentauri** [comment]
I'll take a look at it and I think I can fix it. But I need a tester as I don't have 4TB disk.
Do you have an account on OpenATV or OpenPLi forum so that I can send PM to you?

**Comment by Drickes** [comment]
I´ve  just opened a account on OpenPLI (Drickes)

**Comment by betacentauri** [comment]
I have sent you a PM.

**Comment by betacentauri** [comment]
This should fix the problem:
https://github.com/oe-alliance/ofgwrite/commit/638302c06807b8e4f21e52e885ef6465b7e6aea9

**Comment by Dima73** [comment]
Thahks.
Please update last version for openpli.

**Comment by Drickes** [comment]
when will the new ofgwrite be implemented in automatic full backup?

**Comment by Dima73** [comment]
https://github.com/Dima73/automatic-full-backup/blob/master/enigma2-plugin-extensions-automatic-fullbackup_4.7_all.ipk?raw=true

**Comment by Drickes** [comment]
short feedback: everything works fine with Version 4.7 on VG Ultimo4K with 4TB HDD
Thany you!

**Comment by Dima73** [comment]
thanks betacentauri
