### ISSUE TITLE
Auto fullbackup fail in 664 

### ISSUE THREAD

**Issue by KittyBua** [Dima73/automatic-full-backup#30]
Hey can you fix this 

https://github.com/Dima73/automatic-full-backup/blob/master/src/plugin.py#L664

This fail 

Fail to Datum 21.01.2020 ?? Mmhh

Mfg

**Comment by Dima73** [comment]
[ver. 7.1 - fix output data python3](https://github.com/Dima73/automatic-full-backup/commit/13a8bb573f38aeb2bc2892b8f4d562334617f67b)
[fix tab](https://github.com/Dima73/automatic-full-backup/commit/fd20c753816a09831102a0f3032b532733b0a978)
