### ISSUE TITLE
BackUp on VU+ Uno 4K

### ISSUE THREAD

**Issue by Steinbeisser** [Dima73/automatic-full-backup#4]
First of all a big thanks for this valuable plugin. 
There is a small problem when using the plugin on Uno 4K. As you might know the VU+ Uno 4K flashes the Backup Files by checking the "force.update" file in BackUp folder **without** confirmation by using the power button. This means the Uno4k flashes the Backup when the receiver is booting or rebooting. No confirmation is needed. The "force.update" file can be renamed to "noforce.update" of course but this just helps until next automatic BackUp creation. All files in Backup folder will be deleted and new Backup files will be saved **including** a new "force.update". Would it be possible to include a check for noforce.update and if existing in folder not to create a new force.update? Maybe you have a better solution. 
Anyway, this plugin is a "Must have" for E2.

**Comment by Dima73** [comment]
https://github.com/Dima73/automatic-full-backup/commit/a8a5a423da6be1516f108236dce8c64577ba37e5

**Comment by Steinbeisser** [comment]
The new script works perfectly. Thanks a lot Dimitrij.
