### ISSUE TITLE
Restore won't finish

### ISSUE THREAD

**Issue by ch061441** [Dima73/automatic-full-backup#5]
Hi,
I like this pluging and use it ..... but the first time when I tried to restore a backup made on disk few days before had this problem, Restore started but won't finish ..... had to power off the box and flash from USB.
My box is a VU+ solo 4K.

![restore](https://cloud.githubusercontent.com/assets/25080205/21890988/dc6aa400-d8d0-11e6-9dd6-f010f764c34a.jpg)

**Comment by Dima73** [comment]
This problem is always there for each flasing?
What image?

**Comment by betacentauri** [comment]
Never saw that before. How big is the backup? It stopped at around 95% in step "Writing ext4 rootfs"?

**Comment by ch061441** [comment]
yes, the restore just stop working like the picture, the image is VTI 11.1.
It starts, runs a few minutes and then nothing more, I wait about 10 minutes more but nothing ....

**Comment by betacentauri** [comment]
How big is the backup?
Did you try it a second time?
