### ISSUE TITLE
Backup folder won't be saved

### ISSUE THREAD

**Issue by mat130780** [Dima73/automatic-full-backup#6]
Hi,

on my Solo 4K, I can choose /media/hdd as the backup folder and create a manual backup on my HDD. However, when I leave the plugin (via green button), the backup path will not be saved. Next time I enter the plugin, it just says "None" as backup folder.

**Comment by Dima73** [comment]
Do you have a real mount /media/hdd?
in telnet:
mount

**Comment by mat130780** [comment]
Hi,

I think so. Image is OpenATV 5.3. This is the output:

root@vusolo4k:~# mount
rootfs on / type rootfs (rw)
/dev/root on / type ext4 (rw,relatime,nodelalloc,data=journal)
devtmpfs on /dev type devtmpfs (rw,relatime,size=109984k,nr_inodes=27496,mode=755)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
tmpfs on /media type tmpfs (rw,relatime,size=64k)
tmpfs on /var/volatile type tmpfs (rw,relatime)
/dev/sda1 on /media/hdd type ext4 (rw,relatime,data=ordered)
devpts on /dev/pts type devpts (rw,relatime,gid=5,mode=620)
/etc/auto.network on /media/autofs type autofs (rw,relatime,fd=6,pgrp=739,timeout=5,minproto=5,maxproto=5,indirect)
nfsd on /proc/fs/nfsd type nfsd (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
root@vusolo4k:~#

**Comment by mat130780** [comment]
Video when I enter the plugin, change to /media/hdd and leave with „green“ and then re-enter the plugin: https://youtu.be/u4WWGqAUTh8 <https://youtu.be/u4WWGqAUTh8>

**Comment by mat130780** [comment]
I have now tested it on a fresh install (OpenATV 5.3). Installed plugin version 4.7a and have the same issue: Backup folder path will not be saved after leaving the plugin.
Maybe you can reproduce it that way.

**Comment by Dima73** [comment]
And if you connect and select a USB flash drive?

**Comment by mat130780** [comment]
same issue with an USB flash drive when I select /media/usb
Strangely, I have a NAS and the folder /media/autofs/FRITZ.NAS can be selected and saved.

**Comment by mat130780** [comment]
I re-tested with OpenATV 6.0 and have the same issue there. No issue with current VTI image.
If there is anything I can do to hunt down this bug, please let me know.

**Comment by Dima73** [comment]
OK, I'll check

**Comment by Dima73** [comment]
https://github.com/Dima73/automatic-full-backup/commit/55ca83febd5b154d575a62921d3637ff6b944285

**Comment by mat130780** [comment]
SOLVED!! Thank you!
