### ISSUE TITLE
Error Message Image creation FAILED! 

### ISSUE THREAD

**Issue by Drickes** [Dima73/automatic-full-backup#7]
I use Version 4,7. Ultimo4k and VTI Image 11
When I use the tool for backup i got the error message: Image creation FAILED! 
But it seems that all files are created....
![afb_backup3](https://cloud.githubusercontent.com/assets/24958767/22030755/f7818aa8-dcde-11e6-8bea-c17b2cd75960.jpg)
![afb_backup1](https://cloud.githubusercontent.com/assets/24958767/22030757/f7861d3e-dcde-11e6-9a26-aaefa2d91023.jpg)
![afb_backup2](https://cloud.githubusercontent.com/assets/24958767/22030756/f7825bf4-dcde-11e6-8a52-5dfe0e65d061.jpg)

**Comment by Dima73** [comment]
https://github.com/Dima73/automatic-full-backup/commit/6a016d9e6c1e748778ef1825f29cb0041ff92543

**Comment by Drickes** [comment]
Thank you for your fast help...it works fine now!
