### ISSUE TITLE
Automaticfullbackup on VU+ Ultimo4K crashes enigma2

### ISSUE THREAD

**Issue by GaborDenes95** [Dima73/automatic-full-backup#8]
I am using VTI 11.0.1 with all the current updates and v5 of afb,
but most of the backups in the night crash enigma2 (Display shows the time of the start of the backup, box is reachable via network, enigma2 is shown as defunct())
unfortunately there is nothing in the debug.log which could help.
I had the same issue with all the previous versions as well.
It doesnt matter, if I write the backup to USB-stick(FAT32) or internal hdd(ext4)
Any suggestion what to check?

**Comment by Dima73** [comment]
Which model of the receiver?
Is this problem on other images?

**Comment by Wello72** [comment]
Same problem on VU+ Duo2. 
Image is VTI11 with all Updates. 
Didn't test on other images. 
Box is always on standby, not deep standby. 
Manual backup is working as expected. 
Tried already to backup on HDD and on USB stick.

**Comment by Wello72** [comment]
Forgot one thing. 
The folder with date and timestamp is created on the backup drive at the time setup in the menu of afb.

**Comment by Dima73** [comment]
This is a problem only plugin version 5.1 or all version?
Please run manual backup as "Background mode" for test.

**Comment by Wello72** [comment]
For me on all previous versions and the actual one. 
The manual backup in background mode is working. 
Backup finished in ca 6 minutes on Harddisk. 
No freeze.

**Comment by GaborDenes95** [comment]
The model ist a Ultimo4K (see header)
with Dual DVB-S2-FBC tuner plus dual DVB-S2 tuner
internal 3TB WD Harddisc
I didnt try any other image, only VTI 11.x.x
I started with v4.6 and tried all inbetween upto 5.0
I didnt try v5.1 yet
Update will follow

**Comment by GaborDenes95** [comment]
Just reinstalled v5.0 from the ipk, with the following messages: 
opkg install enigma2-plugin-extensions-automatic-fullbackup_5.0_all.ipk
Installing enigma2-plugin-extensions-automatic-fullbackup (5.0) on root.
enigma2-plugin-extensions-automatic-fullbackup: unsatisfied recommendation for mtd-utils-ubifs
enigma2-plugin-extensions-automatic-fullbackup: unsatisfied recommendation for ofgwrite
enigma2-plugin-extensions-automatic-fullbackup: unsatisfied recommendation for zip
Configuring enigma2-plugin-extensions-automatic-fullbackup.

Update: 
The manual backup in background mode ran successfully

**Comment by Dima73** [comment]
Do you have enough free space on your device?
df -h in telnet

**Comment by GaborDenes95** [comment]
sure I have, 
the backups seem to be completed, even with crashed enigma2
currently I have 
/dev/sdb1                28.9G     12.9G     16.0G  45% /media/usb

But on my Solo4K I didnt have enough free space yesterday and nothing crashed

**Comment by Dima73** [comment]
I think the problem is not with this plugin.
At this time there is no plugin, which wants to put the receiver in the deep standby mode?

**Comment by Dima73** [comment]
/usr/bin/enigma2.sh

add log /tmp

LD_PRELOAD=$LIBS /usr/bin/enigma2 >> /tmp/debug.log 2>&1

or /media/usb

LD_PRELOAD=$LIBS /usr/bin/enigma2 >> /media/usb/debug.log 2>&1

**Comment by GaborDenes95** [comment]
in my latest test, the box was in standby before the start and I use the energy plan to puti into deepstandby after the run (start 4:00, go to dstby 4:30 , but that does not happen as enigma2 crashes at 04:00)
on previous tests, I only used standby, no deepstandby before or after
I created debug logs with VTI options, but debug showed nothing
I´ll give it a try, when there are no planned recordings.

btw. the Ultimo4K usually never goes to deepstandby, I just added it as it was suggested by the vti-forum.

**Comment by Wello72** [comment]
Hi,

i have tested again with the "extended" logging active, below the part of the log:
[debug.log.txt](https://github.com/Dima73/automatic-full-backup/files/846916/debug.log.txt)

Seems that the backup was successfull, DUO2 is reachable via network, but i can't weakup the receiver from standby. The clock in the display is still at 01:00 (freeze). `

**Comment by Dima73** [comment]
What is this log?
 LD_PRELOAD=$LIBS /usr/bin/enigma2 >> /tmp/debug.log 2>&1 ?

**Comment by Wello72** [comment]
This is the debug log from the /tmp after adding it to enigma2.sh and run the afb this night at 01:00.

**Comment by Dima73** [comment]
Is this the whole log?

**Comment by Wello72** [comment]
No, only the last lines after afb script s started. 

Forgot to copy the debug log after reboot.

If you need the complete log, I will provide it in the next days. Was not aware that you need the complete one. Sorry

**Comment by GaborDenes95** [comment]
As this thread is getting messed up  (Its about an Ultimo4K , not Duo or other models) I am leaving it.
the last two backups have been created without crashing enigma2
 (only change from my side was a different start time, becaues of planned recordings)
